import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

/**
 * Localization migration — converts non-localized text columns into per-locale rows
 * across 28 new `_locales` tables. PRESERVES existing CMS data via INSERT ... SELECT
 * statements that run BEFORE the DROP COLUMN steps.
 *
 * Data flow per source row:
 *   1. Copy English value from old column → new locales table with _locale='en'
 *   2. If a legacy `chinese*` companion column has a non-NULL value, copy that
 *      → new locales table with _locale='zh'
 *
 * Affected blocks: hero (+ stats, cta_buttons), stats (+ stats), values
 * (+ four_harmonies_items, five_unities_items, mottos), about (+ advantages),
 * services (+ services), platform_teaser (+ features). Plus all `_pages_v_*`
 * version-history tables.
 *
 * This migration is paired with backup `cms_backup_20260504` — see
 * docs/improvements/infrastructure/cms-backup-runbook.md for restore steps.
 *
 * Generated by `payload migrate:create` then HAND-EDITED to add data preservation.
 * Anything between the "── DATA COPY ──" markers is hand-written; everything
 * else came from the auto-generated diff.
 */
export async function up({ db, payload: _payload, req: _req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "cms"."_locales" AS ENUM('en', 'zh');
  CREATE TYPE "cms"."enum__pages_v_published_locale" AS ENUM('en', 'zh');
  CREATE TABLE "cms"."pages_blocks_hero_stats_locales" (
  	"label" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "cms"."_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );

  CREATE TABLE "cms"."pages_blocks_hero_cta_buttons_locales" (
  	"label" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "cms"."_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );

  CREATE TABLE "cms"."pages_blocks_hero_locales" (
  	"eyebrow" varchar,
  	"headline" varchar,
  	"headline_accent" varchar,
  	"headline_faint" varchar,
  	"subtitle" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "cms"."_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );

  CREATE TABLE "cms"."pages_blocks_stats_stats_locales" (
  	"label" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "cms"."_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );

  CREATE TABLE "cms"."pages_blocks_values_four_harmonies_items_locales" (
  	"english" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "cms"."_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );

  CREATE TABLE "cms"."pages_blocks_values_five_unities_items_locales" (
  	"english" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "cms"."_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );

  CREATE TABLE "cms"."pages_blocks_values_mottos_locales" (
  	"label" varchar,
  	"english" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "cms"."_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );

  CREATE TABLE "cms"."pages_blocks_values_locales" (
  	"section_label" varchar,
  	"headline" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "cms"."_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );

  CREATE TABLE "cms"."pages_blocks_about_advantages_locales" (
  	"title" varchar,
  	"description" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "cms"."_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );

  CREATE TABLE "cms"."pages_blocks_about_locales" (
  	"section_label" varchar,
  	"headline" varchar,
  	"headline_accent" varchar,
  	"body" jsonb,
  	"globe_stat_label" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "cms"."_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );

  CREATE TABLE "cms"."pages_blocks_services_services_locales" (
  	"title" varchar,
  	"description" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "cms"."_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );

  CREATE TABLE "cms"."pages_blocks_services_locales" (
  	"section_label" varchar,
  	"headline" varchar,
  	"headline_accent" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "cms"."_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );

  CREATE TABLE "cms"."pages_blocks_platform_teaser_features_locales" (
  	"title" varchar,
  	"description" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "cms"."_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );

  CREATE TABLE "cms"."pages_blocks_platform_teaser_locales" (
  	"section_label" varchar,
  	"headline" varchar,
  	"headline_accent" varchar,
  	"body" jsonb,
  	"launch_cta_label" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "cms"."_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );

  CREATE TABLE "cms"."_pages_v_blocks_hero_stats_locales" (
  	"label" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "cms"."_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );

  CREATE TABLE "cms"."_pages_v_blocks_hero_cta_buttons_locales" (
  	"label" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "cms"."_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );

  CREATE TABLE "cms"."_pages_v_blocks_hero_locales" (
  	"eyebrow" varchar,
  	"headline" varchar,
  	"headline_accent" varchar,
  	"headline_faint" varchar,
  	"subtitle" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "cms"."_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );

  CREATE TABLE "cms"."_pages_v_blocks_stats_stats_locales" (
  	"label" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "cms"."_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );

  CREATE TABLE "cms"."_pages_v_blocks_values_four_harmonies_items_locales" (
  	"english" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "cms"."_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );

  CREATE TABLE "cms"."_pages_v_blocks_values_five_unities_items_locales" (
  	"english" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "cms"."_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );

  CREATE TABLE "cms"."_pages_v_blocks_values_mottos_locales" (
  	"label" varchar,
  	"english" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "cms"."_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );

  CREATE TABLE "cms"."_pages_v_blocks_values_locales" (
  	"section_label" varchar,
  	"headline" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "cms"."_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );

  CREATE TABLE "cms"."_pages_v_blocks_about_advantages_locales" (
  	"title" varchar,
  	"description" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "cms"."_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );

  CREATE TABLE "cms"."_pages_v_blocks_about_locales" (
  	"section_label" varchar,
  	"headline" varchar,
  	"headline_accent" varchar,
  	"body" jsonb,
  	"globe_stat_label" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "cms"."_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );

  CREATE TABLE "cms"."_pages_v_blocks_services_services_locales" (
  	"title" varchar,
  	"description" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "cms"."_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );

  CREATE TABLE "cms"."_pages_v_blocks_services_locales" (
  	"section_label" varchar,
  	"headline" varchar,
  	"headline_accent" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "cms"."_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );

  CREATE TABLE "cms"."_pages_v_blocks_platform_teaser_features_locales" (
  	"title" varchar,
  	"description" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "cms"."_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );

  CREATE TABLE "cms"."_pages_v_blocks_platform_teaser_locales" (
  	"section_label" varchar,
  	"headline" varchar,
  	"headline_accent" varchar,
  	"body" jsonb,
  	"launch_cta_label" varchar,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "cms"."_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );

  DROP INDEX IF EXISTS "cms"."_pages_v_autosave_idx";
  ALTER TABLE "cms"."_pages_v" ADD COLUMN "snapshot" boolean;
  ALTER TABLE "cms"."_pages_v" ADD COLUMN "published_locale" "cms"."enum__pages_v_published_locale";
  ALTER TABLE "cms"."platform_settings" ADD COLUMN "contact_modal_heading" varchar DEFAULT 'Connect with this partner · 联系合作方';
  ALTER TABLE "cms"."platform_settings" ADD COLUMN "contact_modal_success_title" varchar DEFAULT 'Introduction Sent!';
  ALTER TABLE "cms"."platform_settings" ADD COLUMN "contact_modal_success_message" varchar DEFAULT 'WeConnect will facilitate the connection within 1–2 business days. · 已发送，1-2个工作日内回复。';
  ALTER TABLE "cms"."platform_settings" ADD COLUMN "detail_label_size" varchar DEFAULT 'Size';
  ALTER TABLE "cms"."platform_settings" ADD COLUMN "detail_label_zone" varchar DEFAULT 'Zone';
  ALTER TABLE "cms"."platform_settings" ADD COLUMN "detail_label_setup" varchar DEFAULT 'Setup';
  ALTER TABLE "cms"."platform_settings" ADD COLUMN "detail_label_lease" varchar DEFAULT 'Lease';
  ALTER TABLE "cms"."platform_settings" ADD COLUMN "detail_label_price" varchar DEFAULT 'Price';
  ALTER TABLE "cms"."platform_settings" ADD COLUMN "requirement_modal_heading" varchar DEFAULT 'Post a Requirement · 发布需求';
  ALTER TABLE "cms"."platform_settings" ADD COLUMN "requirement_modal_description" varchar DEFAULT 'Tell the WeConnect network what you need';
  ALTER TABLE "cms"."platform_settings" ADD COLUMN "requirement_modal_success_title" varchar DEFAULT 'Requirement Posted!';
  ALTER TABLE "cms"."platform_settings" ADD COLUMN "requirement_modal_success_message" varchar DEFAULT 'AI is matching with verified partners. You''ll hear back within 24–48 hours. · AI正在匹配认证合作伙伴，24-48小时内回复。';
  ALTER TABLE "cms"."pages_blocks_hero_stats_locales" ADD CONSTRAINT "pages_blocks_hero_stats_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "cms"."pages_blocks_hero_stats"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "cms"."pages_blocks_hero_cta_buttons_locales" ADD CONSTRAINT "pages_blocks_hero_cta_buttons_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "cms"."pages_blocks_hero_cta_buttons"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "cms"."pages_blocks_hero_locales" ADD CONSTRAINT "pages_blocks_hero_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "cms"."pages_blocks_hero"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "cms"."pages_blocks_stats_stats_locales" ADD CONSTRAINT "pages_blocks_stats_stats_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "cms"."pages_blocks_stats_stats"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "cms"."pages_blocks_values_four_harmonies_items_locales" ADD CONSTRAINT "pages_blocks_values_four_harmonies_items_locales_parent_i_fk" FOREIGN KEY ("_parent_id") REFERENCES "cms"."pages_blocks_values_four_harmonies_items"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "cms"."pages_blocks_values_five_unities_items_locales" ADD CONSTRAINT "pages_blocks_values_five_unities_items_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "cms"."pages_blocks_values_five_unities_items"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "cms"."pages_blocks_values_mottos_locales" ADD CONSTRAINT "pages_blocks_values_mottos_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "cms"."pages_blocks_values_mottos"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "cms"."pages_blocks_values_locales" ADD CONSTRAINT "pages_blocks_values_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "cms"."pages_blocks_values"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "cms"."pages_blocks_about_advantages_locales" ADD CONSTRAINT "pages_blocks_about_advantages_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "cms"."pages_blocks_about_advantages"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "cms"."pages_blocks_about_locales" ADD CONSTRAINT "pages_blocks_about_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "cms"."pages_blocks_about"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "cms"."pages_blocks_services_services_locales" ADD CONSTRAINT "pages_blocks_services_services_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "cms"."pages_blocks_services_services"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "cms"."pages_blocks_services_locales" ADD CONSTRAINT "pages_blocks_services_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "cms"."pages_blocks_services"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "cms"."pages_blocks_platform_teaser_features_locales" ADD CONSTRAINT "pages_blocks_platform_teaser_features_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "cms"."pages_blocks_platform_teaser_features"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "cms"."pages_blocks_platform_teaser_locales" ADD CONSTRAINT "pages_blocks_platform_teaser_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "cms"."pages_blocks_platform_teaser"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "cms"."_pages_v_blocks_hero_stats_locales" ADD CONSTRAINT "_pages_v_blocks_hero_stats_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "cms"."_pages_v_blocks_hero_stats"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "cms"."_pages_v_blocks_hero_cta_buttons_locales" ADD CONSTRAINT "_pages_v_blocks_hero_cta_buttons_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "cms"."_pages_v_blocks_hero_cta_buttons"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "cms"."_pages_v_blocks_hero_locales" ADD CONSTRAINT "_pages_v_blocks_hero_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "cms"."_pages_v_blocks_hero"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "cms"."_pages_v_blocks_stats_stats_locales" ADD CONSTRAINT "_pages_v_blocks_stats_stats_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "cms"."_pages_v_blocks_stats_stats"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "cms"."_pages_v_blocks_values_four_harmonies_items_locales" ADD CONSTRAINT "_pages_v_blocks_values_four_harmonies_items_locales_paren_fk" FOREIGN KEY ("_parent_id") REFERENCES "cms"."_pages_v_blocks_values_four_harmonies_items"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "cms"."_pages_v_blocks_values_five_unities_items_locales" ADD CONSTRAINT "_pages_v_blocks_values_five_unities_items_locales_parent__fk" FOREIGN KEY ("_parent_id") REFERENCES "cms"."_pages_v_blocks_values_five_unities_items"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "cms"."_pages_v_blocks_values_mottos_locales" ADD CONSTRAINT "_pages_v_blocks_values_mottos_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "cms"."_pages_v_blocks_values_mottos"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "cms"."_pages_v_blocks_values_locales" ADD CONSTRAINT "_pages_v_blocks_values_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "cms"."_pages_v_blocks_values"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "cms"."_pages_v_blocks_about_advantages_locales" ADD CONSTRAINT "_pages_v_blocks_about_advantages_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "cms"."_pages_v_blocks_about_advantages"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "cms"."_pages_v_blocks_about_locales" ADD CONSTRAINT "_pages_v_blocks_about_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "cms"."_pages_v_blocks_about"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "cms"."_pages_v_blocks_services_services_locales" ADD CONSTRAINT "_pages_v_blocks_services_services_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "cms"."_pages_v_blocks_services_services"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "cms"."_pages_v_blocks_services_locales" ADD CONSTRAINT "_pages_v_blocks_services_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "cms"."_pages_v_blocks_services"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "cms"."_pages_v_blocks_platform_teaser_features_locales" ADD CONSTRAINT "_pages_v_blocks_platform_teaser_features_locales_parent_i_fk" FOREIGN KEY ("_parent_id") REFERENCES "cms"."_pages_v_blocks_platform_teaser_features"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "cms"."_pages_v_blocks_platform_teaser_locales" ADD CONSTRAINT "_pages_v_blocks_platform_teaser_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "cms"."_pages_v_blocks_platform_teaser"("id") ON DELETE cascade ON UPDATE no action;
  CREATE UNIQUE INDEX "pages_blocks_hero_stats_locales_locale_parent_id_unique" ON "cms"."pages_blocks_hero_stats_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "pages_blocks_hero_cta_buttons_locales_locale_parent_id_uniqu" ON "cms"."pages_blocks_hero_cta_buttons_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "pages_blocks_hero_locales_locale_parent_id_unique" ON "cms"."pages_blocks_hero_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "pages_blocks_stats_stats_locales_locale_parent_id_unique" ON "cms"."pages_blocks_stats_stats_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "pages_blocks_values_four_harmonies_items_locales_locale_pare" ON "cms"."pages_blocks_values_four_harmonies_items_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "pages_blocks_values_five_unities_items_locales_locale_parent" ON "cms"."pages_blocks_values_five_unities_items_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "pages_blocks_values_mottos_locales_locale_parent_id_unique" ON "cms"."pages_blocks_values_mottos_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "pages_blocks_values_locales_locale_parent_id_unique" ON "cms"."pages_blocks_values_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "pages_blocks_about_advantages_locales_locale_parent_id_uniqu" ON "cms"."pages_blocks_about_advantages_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "pages_blocks_about_locales_locale_parent_id_unique" ON "cms"."pages_blocks_about_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "pages_blocks_services_services_locales_locale_parent_id_uniq" ON "cms"."pages_blocks_services_services_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "pages_blocks_services_locales_locale_parent_id_unique" ON "cms"."pages_blocks_services_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "pages_blocks_platform_teaser_features_locales_locale_parent_" ON "cms"."pages_blocks_platform_teaser_features_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "pages_blocks_platform_teaser_locales_locale_parent_id_unique" ON "cms"."pages_blocks_platform_teaser_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "_pages_v_blocks_hero_stats_locales_locale_parent_id_unique" ON "cms"."_pages_v_blocks_hero_stats_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "_pages_v_blocks_hero_cta_buttons_locales_locale_parent_id_un" ON "cms"."_pages_v_blocks_hero_cta_buttons_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "_pages_v_blocks_hero_locales_locale_parent_id_unique" ON "cms"."_pages_v_blocks_hero_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "_pages_v_blocks_stats_stats_locales_locale_parent_id_unique" ON "cms"."_pages_v_blocks_stats_stats_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "_pages_v_blocks_values_four_harmonies_items_locales_locale_p" ON "cms"."_pages_v_blocks_values_four_harmonies_items_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "_pages_v_blocks_values_five_unities_items_locales_locale_par" ON "cms"."_pages_v_blocks_values_five_unities_items_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "_pages_v_blocks_values_mottos_locales_locale_parent_id_uniqu" ON "cms"."_pages_v_blocks_values_mottos_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "_pages_v_blocks_values_locales_locale_parent_id_unique" ON "cms"."_pages_v_blocks_values_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "_pages_v_blocks_about_advantages_locales_locale_parent_id_un" ON "cms"."_pages_v_blocks_about_advantages_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "_pages_v_blocks_about_locales_locale_parent_id_unique" ON "cms"."_pages_v_blocks_about_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "_pages_v_blocks_services_services_locales_locale_parent_id_u" ON "cms"."_pages_v_blocks_services_services_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "_pages_v_blocks_services_locales_locale_parent_id_unique" ON "cms"."_pages_v_blocks_services_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "_pages_v_blocks_platform_teaser_features_locales_locale_pare" ON "cms"."_pages_v_blocks_platform_teaser_features_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "_pages_v_blocks_platform_teaser_locales_locale_parent_id_uni" ON "cms"."_pages_v_blocks_platform_teaser_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_pages_v_snapshot_idx" ON "cms"."_pages_v" USING btree ("snapshot");
  CREATE INDEX "_pages_v_published_locale_idx" ON "cms"."_pages_v" USING btree ("published_locale");
  `)

  // ─────────────────────────────────────────────────────────────────────────
  // ── DATA COPY (HAND-WRITTEN) ──────────────────────────────────────────────
  // Copies values from old non-localized columns into new _locales tables
  // BEFORE the DROP COLUMN steps below remove them.
  //
  // Pattern per source row:
  //   • Always copy English columns → _locales row with _locale='en'
  //   • If a row's chinese_* companion is non-NULL, also create _locale='zh' row
  //
  // For nested arrays (stats, cta_buttons, services, advantages, mottos,
  // four_harmonies_items, five_unities_items, features), only an English
  // copy is created — those tables don't have legacy chinese* companions
  // (translated text was stored on the parent block as `chineseHeadline` etc).
  //
  // Version (`_pages_v_*`) tables get the same treatment.
  // ─────────────────────────────────────────────────────────────────────────

  // ── pages_blocks_hero ──
  await db.execute(sql`
    INSERT INTO "cms"."pages_blocks_hero_locales" ("_locale", "_parent_id", "eyebrow", "headline", "headline_accent", "headline_faint")
    SELECT 'en', "id", "eyebrow", "headline", "headline_accent", "headline_faint"
    FROM "cms"."pages_blocks_hero"
    WHERE "eyebrow" IS NOT NULL OR "headline" IS NOT NULL OR "headline_accent" IS NOT NULL OR "headline_faint" IS NOT NULL;
  `)
  await db.execute(sql`
    INSERT INTO "cms"."pages_blocks_hero_locales" ("_locale", "_parent_id", "subtitle")
    SELECT 'zh', "id", "chinese_subtitle"
    FROM "cms"."pages_blocks_hero"
    WHERE "chinese_subtitle" IS NOT NULL;
  `)

  // ── pages_blocks_hero_stats (array) ──
  await db.execute(sql`
    INSERT INTO "cms"."pages_blocks_hero_stats_locales" ("_locale", "_parent_id", "label")
    SELECT 'en', "id", "label"
    FROM "cms"."pages_blocks_hero_stats"
    WHERE "label" IS NOT NULL;
  `)
  await db.execute(sql`
    INSERT INTO "cms"."pages_blocks_hero_stats_locales" ("_locale", "_parent_id", "label")
    SELECT 'zh', "id", "chinese_label"
    FROM "cms"."pages_blocks_hero_stats"
    WHERE "chinese_label" IS NOT NULL;
  `)

  // ── pages_blocks_hero_cta_buttons (array) — no chinese companion ──
  await db.execute(sql`
    INSERT INTO "cms"."pages_blocks_hero_cta_buttons_locales" ("_locale", "_parent_id", "label")
    SELECT 'en', "id", "label"
    FROM "cms"."pages_blocks_hero_cta_buttons"
    WHERE "label" IS NOT NULL;
  `)

  // ── pages_blocks_stats_stats (array) — chinese_label companion ──
  await db.execute(sql`
    INSERT INTO "cms"."pages_blocks_stats_stats_locales" ("_locale", "_parent_id", "label")
    SELECT 'en', "id", "label"
    FROM "cms"."pages_blocks_stats_stats"
    WHERE "label" IS NOT NULL;
  `)
  await db.execute(sql`
    INSERT INTO "cms"."pages_blocks_stats_stats_locales" ("_locale", "_parent_id", "label")
    SELECT 'zh', "id", "chinese_label"
    FROM "cms"."pages_blocks_stats_stats"
    WHERE "chinese_label" IS NOT NULL;
  `)

  // ── pages_blocks_values ──
  await db.execute(sql`
    INSERT INTO "cms"."pages_blocks_values_locales" ("_locale", "_parent_id", "section_label", "headline")
    SELECT 'en', "id", "section_label", "headline"
    FROM "cms"."pages_blocks_values"
    WHERE "section_label" IS NOT NULL OR "headline" IS NOT NULL;
  `)
  await db.execute(sql`
    INSERT INTO "cms"."pages_blocks_values_locales" ("_locale", "_parent_id", "headline")
    SELECT 'zh', "id", "chinese_headline"
    FROM "cms"."pages_blocks_values"
    WHERE "chinese_headline" IS NOT NULL;
  `)

  // ── pages_blocks_values_four_harmonies_items (array) — `english` is the EN
  //    text; the `chinese` field is decorative (single character) and stays
  //    on the parent table, NOT migrated to _locales ──
  await db.execute(sql`
    INSERT INTO "cms"."pages_blocks_values_four_harmonies_items_locales" ("_locale", "_parent_id", "english")
    SELECT 'en', "id", "english"
    FROM "cms"."pages_blocks_values_four_harmonies_items"
    WHERE "english" IS NOT NULL;
  `)

  // ── pages_blocks_values_five_unities_items (array) — same pattern ──
  await db.execute(sql`
    INSERT INTO "cms"."pages_blocks_values_five_unities_items_locales" ("_locale", "_parent_id", "english")
    SELECT 'en', "id", "english"
    FROM "cms"."pages_blocks_values_five_unities_items"
    WHERE "english" IS NOT NULL;
  `)

  // ── pages_blocks_values_mottos (array) — `english` + `label` are EN text;
  //    `chinese` is decorative and stays on parent ──
  await db.execute(sql`
    INSERT INTO "cms"."pages_blocks_values_mottos_locales" ("_locale", "_parent_id", "label", "english")
    SELECT 'en', "id", "label", "english"
    FROM "cms"."pages_blocks_values_mottos"
    WHERE "label" IS NOT NULL OR "english" IS NOT NULL;
  `)

  // ── pages_blocks_about ──
  await db.execute(sql`
    INSERT INTO "cms"."pages_blocks_about_locales" ("_locale", "_parent_id", "section_label", "headline", "headline_accent", "body", "globe_stat_label")
    SELECT 'en', "id", "section_label", "headline", "headline_accent", "body", "globe_stat_label"
    FROM "cms"."pages_blocks_about"
    WHERE "section_label" IS NOT NULL OR "headline" IS NOT NULL OR "headline_accent" IS NOT NULL OR "body" IS NOT NULL OR "globe_stat_label" IS NOT NULL;
  `)

  // ── pages_blocks_about_advantages (array) — no chinese companion ──
  await db.execute(sql`
    INSERT INTO "cms"."pages_blocks_about_advantages_locales" ("_locale", "_parent_id", "title", "description")
    SELECT 'en', "id", "title", "description"
    FROM "cms"."pages_blocks_about_advantages"
    WHERE "title" IS NOT NULL OR "description" IS NOT NULL;
  `)

  // ── pages_blocks_services ──
  await db.execute(sql`
    INSERT INTO "cms"."pages_blocks_services_locales" ("_locale", "_parent_id", "section_label", "headline", "headline_accent")
    SELECT 'en', "id", "section_label", "headline", "headline_accent"
    FROM "cms"."pages_blocks_services"
    WHERE "section_label" IS NOT NULL OR "headline" IS NOT NULL OR "headline_accent" IS NOT NULL;
  `)

  // ── pages_blocks_services_services (array) — chinese_title companion ──
  await db.execute(sql`
    INSERT INTO "cms"."pages_blocks_services_services_locales" ("_locale", "_parent_id", "title", "description")
    SELECT 'en', "id", "title", "description"
    FROM "cms"."pages_blocks_services_services"
    WHERE "title" IS NOT NULL OR "description" IS NOT NULL;
  `)
  await db.execute(sql`
    INSERT INTO "cms"."pages_blocks_services_services_locales" ("_locale", "_parent_id", "title")
    SELECT 'zh', "id", "chinese_title"
    FROM "cms"."pages_blocks_services_services"
    WHERE "chinese_title" IS NOT NULL;
  `)

  // ── pages_blocks_platform_teaser ──
  await db.execute(sql`
    INSERT INTO "cms"."pages_blocks_platform_teaser_locales" ("_locale", "_parent_id", "section_label", "headline", "headline_accent", "body", "launch_cta_label")
    SELECT 'en', "id", "section_label", "headline", "headline_accent", "body", "launch_cta_label"
    FROM "cms"."pages_blocks_platform_teaser"
    WHERE "section_label" IS NOT NULL OR "headline" IS NOT NULL OR "headline_accent" IS NOT NULL OR "body" IS NOT NULL OR "launch_cta_label" IS NOT NULL;
  `)

  // ── pages_blocks_platform_teaser_features (array) — no chinese companion ──
  await db.execute(sql`
    INSERT INTO "cms"."pages_blocks_platform_teaser_features_locales" ("_locale", "_parent_id", "title", "description")
    SELECT 'en', "id", "title", "description"
    FROM "cms"."pages_blocks_platform_teaser_features"
    WHERE "title" IS NOT NULL OR "description" IS NOT NULL;
  `)

  // ── _pages_v_* version tables — same pattern as parent counterparts ──
  await db.execute(sql`
    INSERT INTO "cms"."_pages_v_blocks_hero_locales" ("_locale", "_parent_id", "eyebrow", "headline", "headline_accent", "headline_faint")
    SELECT 'en', "id", "eyebrow", "headline", "headline_accent", "headline_faint"
    FROM "cms"."_pages_v_blocks_hero"
    WHERE "eyebrow" IS NOT NULL OR "headline" IS NOT NULL OR "headline_accent" IS NOT NULL OR "headline_faint" IS NOT NULL;
  `)
  await db.execute(sql`
    INSERT INTO "cms"."_pages_v_blocks_hero_locales" ("_locale", "_parent_id", "subtitle")
    SELECT 'zh', "id", "chinese_subtitle"
    FROM "cms"."_pages_v_blocks_hero"
    WHERE "chinese_subtitle" IS NOT NULL;
  `)
  await db.execute(sql`
    INSERT INTO "cms"."_pages_v_blocks_hero_stats_locales" ("_locale", "_parent_id", "label")
    SELECT 'en', "id", "label"
    FROM "cms"."_pages_v_blocks_hero_stats"
    WHERE "label" IS NOT NULL;
  `)
  await db.execute(sql`
    INSERT INTO "cms"."_pages_v_blocks_hero_stats_locales" ("_locale", "_parent_id", "label")
    SELECT 'zh', "id", "chinese_label"
    FROM "cms"."_pages_v_blocks_hero_stats"
    WHERE "chinese_label" IS NOT NULL;
  `)
  await db.execute(sql`
    INSERT INTO "cms"."_pages_v_blocks_hero_cta_buttons_locales" ("_locale", "_parent_id", "label")
    SELECT 'en', "id", "label"
    FROM "cms"."_pages_v_blocks_hero_cta_buttons"
    WHERE "label" IS NOT NULL;
  `)
  await db.execute(sql`
    INSERT INTO "cms"."_pages_v_blocks_stats_stats_locales" ("_locale", "_parent_id", "label")
    SELECT 'en', "id", "label"
    FROM "cms"."_pages_v_blocks_stats_stats"
    WHERE "label" IS NOT NULL;
  `)
  await db.execute(sql`
    INSERT INTO "cms"."_pages_v_blocks_stats_stats_locales" ("_locale", "_parent_id", "label")
    SELECT 'zh', "id", "chinese_label"
    FROM "cms"."_pages_v_blocks_stats_stats"
    WHERE "chinese_label" IS NOT NULL;
  `)
  await db.execute(sql`
    INSERT INTO "cms"."_pages_v_blocks_values_locales" ("_locale", "_parent_id", "section_label", "headline")
    SELECT 'en', "id", "section_label", "headline"
    FROM "cms"."_pages_v_blocks_values"
    WHERE "section_label" IS NOT NULL OR "headline" IS NOT NULL;
  `)
  await db.execute(sql`
    INSERT INTO "cms"."_pages_v_blocks_values_locales" ("_locale", "_parent_id", "headline")
    SELECT 'zh', "id", "chinese_headline"
    FROM "cms"."_pages_v_blocks_values"
    WHERE "chinese_headline" IS NOT NULL;
  `)
  await db.execute(sql`
    INSERT INTO "cms"."_pages_v_blocks_values_four_harmonies_items_locales" ("_locale", "_parent_id", "english")
    SELECT 'en', "id", "english"
    FROM "cms"."_pages_v_blocks_values_four_harmonies_items"
    WHERE "english" IS NOT NULL;
  `)
  await db.execute(sql`
    INSERT INTO "cms"."_pages_v_blocks_values_five_unities_items_locales" ("_locale", "_parent_id", "english")
    SELECT 'en', "id", "english"
    FROM "cms"."_pages_v_blocks_values_five_unities_items"
    WHERE "english" IS NOT NULL;
  `)
  await db.execute(sql`
    INSERT INTO "cms"."_pages_v_blocks_values_mottos_locales" ("_locale", "_parent_id", "label", "english")
    SELECT 'en', "id", "label", "english"
    FROM "cms"."_pages_v_blocks_values_mottos"
    WHERE "label" IS NOT NULL OR "english" IS NOT NULL;
  `)
  await db.execute(sql`
    INSERT INTO "cms"."_pages_v_blocks_about_locales" ("_locale", "_parent_id", "section_label", "headline", "headline_accent", "body", "globe_stat_label")
    SELECT 'en', "id", "section_label", "headline", "headline_accent", "body", "globe_stat_label"
    FROM "cms"."_pages_v_blocks_about"
    WHERE "section_label" IS NOT NULL OR "headline" IS NOT NULL OR "headline_accent" IS NOT NULL OR "body" IS NOT NULL OR "globe_stat_label" IS NOT NULL;
  `)
  await db.execute(sql`
    INSERT INTO "cms"."_pages_v_blocks_about_advantages_locales" ("_locale", "_parent_id", "title", "description")
    SELECT 'en', "id", "title", "description"
    FROM "cms"."_pages_v_blocks_about_advantages"
    WHERE "title" IS NOT NULL OR "description" IS NOT NULL;
  `)
  await db.execute(sql`
    INSERT INTO "cms"."_pages_v_blocks_services_locales" ("_locale", "_parent_id", "section_label", "headline", "headline_accent")
    SELECT 'en', "id", "section_label", "headline", "headline_accent"
    FROM "cms"."_pages_v_blocks_services"
    WHERE "section_label" IS NOT NULL OR "headline" IS NOT NULL OR "headline_accent" IS NOT NULL;
  `)
  await db.execute(sql`
    INSERT INTO "cms"."_pages_v_blocks_services_services_locales" ("_locale", "_parent_id", "title", "description")
    SELECT 'en', "id", "title", "description"
    FROM "cms"."_pages_v_blocks_services_services"
    WHERE "title" IS NOT NULL OR "description" IS NOT NULL;
  `)
  await db.execute(sql`
    INSERT INTO "cms"."_pages_v_blocks_services_services_locales" ("_locale", "_parent_id", "title")
    SELECT 'zh', "id", "chinese_title"
    FROM "cms"."_pages_v_blocks_services_services"
    WHERE "chinese_title" IS NOT NULL;
  `)
  await db.execute(sql`
    INSERT INTO "cms"."_pages_v_blocks_platform_teaser_locales" ("_locale", "_parent_id", "section_label", "headline", "headline_accent", "body", "launch_cta_label")
    SELECT 'en', "id", "section_label", "headline", "headline_accent", "body", "launch_cta_label"
    FROM "cms"."_pages_v_blocks_platform_teaser"
    WHERE "section_label" IS NOT NULL OR "headline" IS NOT NULL OR "headline_accent" IS NOT NULL OR "body" IS NOT NULL OR "launch_cta_label" IS NOT NULL;
  `)
  await db.execute(sql`
    INSERT INTO "cms"."_pages_v_blocks_platform_teaser_features_locales" ("_locale", "_parent_id", "title", "description")
    SELECT 'en', "id", "title", "description"
    FROM "cms"."_pages_v_blocks_platform_teaser_features"
    WHERE "title" IS NOT NULL OR "description" IS NOT NULL;
  `)

  // ─────────────────────────────────────────────────────────────────────────
  // ── DROP COLUMNS (auto-generated, safe now that data is preserved) ───────
  // ─────────────────────────────────────────────────────────────────────────
  await db.execute(sql`
  ALTER TABLE "cms"."pages_blocks_hero_stats" DROP COLUMN IF EXISTS "label";
  ALTER TABLE "cms"."pages_blocks_hero_cta_buttons" DROP COLUMN IF EXISTS "label";
  ALTER TABLE "cms"."pages_blocks_hero" DROP COLUMN IF EXISTS "eyebrow";
  ALTER TABLE "cms"."pages_blocks_hero" DROP COLUMN IF EXISTS "headline";
  ALTER TABLE "cms"."pages_blocks_hero" DROP COLUMN IF EXISTS "headline_accent";
  ALTER TABLE "cms"."pages_blocks_hero" DROP COLUMN IF EXISTS "headline_faint";
  ALTER TABLE "cms"."pages_blocks_stats_stats" DROP COLUMN IF EXISTS "label";
  ALTER TABLE "cms"."pages_blocks_values_four_harmonies_items" DROP COLUMN IF EXISTS "english";
  ALTER TABLE "cms"."pages_blocks_values_five_unities_items" DROP COLUMN IF EXISTS "english";
  ALTER TABLE "cms"."pages_blocks_values_mottos" DROP COLUMN IF EXISTS "label";
  ALTER TABLE "cms"."pages_blocks_values_mottos" DROP COLUMN IF EXISTS "english";
  ALTER TABLE "cms"."pages_blocks_values" DROP COLUMN IF EXISTS "section_label";
  ALTER TABLE "cms"."pages_blocks_values" DROP COLUMN IF EXISTS "headline";
  ALTER TABLE "cms"."pages_blocks_about_advantages" DROP COLUMN IF EXISTS "title";
  ALTER TABLE "cms"."pages_blocks_about_advantages" DROP COLUMN IF EXISTS "description";
  ALTER TABLE "cms"."pages_blocks_about" DROP COLUMN IF EXISTS "section_label";
  ALTER TABLE "cms"."pages_blocks_about" DROP COLUMN IF EXISTS "headline";
  ALTER TABLE "cms"."pages_blocks_about" DROP COLUMN IF EXISTS "headline_accent";
  ALTER TABLE "cms"."pages_blocks_about" DROP COLUMN IF EXISTS "body";
  ALTER TABLE "cms"."pages_blocks_about" DROP COLUMN IF EXISTS "globe_stat_label";
  ALTER TABLE "cms"."pages_blocks_services_services" DROP COLUMN IF EXISTS "title";
  ALTER TABLE "cms"."pages_blocks_services_services" DROP COLUMN IF EXISTS "description";
  ALTER TABLE "cms"."pages_blocks_services" DROP COLUMN IF EXISTS "section_label";
  ALTER TABLE "cms"."pages_blocks_services" DROP COLUMN IF EXISTS "headline";
  ALTER TABLE "cms"."pages_blocks_services" DROP COLUMN IF EXISTS "headline_accent";
  ALTER TABLE "cms"."pages_blocks_platform_teaser_features" DROP COLUMN IF EXISTS "title";
  ALTER TABLE "cms"."pages_blocks_platform_teaser_features" DROP COLUMN IF EXISTS "description";
  ALTER TABLE "cms"."pages_blocks_platform_teaser" DROP COLUMN IF EXISTS "section_label";
  ALTER TABLE "cms"."pages_blocks_platform_teaser" DROP COLUMN IF EXISTS "headline";
  ALTER TABLE "cms"."pages_blocks_platform_teaser" DROP COLUMN IF EXISTS "headline_accent";
  ALTER TABLE "cms"."pages_blocks_platform_teaser" DROP COLUMN IF EXISTS "body";
  ALTER TABLE "cms"."pages_blocks_platform_teaser" DROP COLUMN IF EXISTS "launch_cta_label";
  ALTER TABLE "cms"."_pages_v_blocks_hero_stats" DROP COLUMN IF EXISTS "label";
  ALTER TABLE "cms"."_pages_v_blocks_hero_cta_buttons" DROP COLUMN IF EXISTS "label";
  ALTER TABLE "cms"."_pages_v_blocks_hero" DROP COLUMN IF EXISTS "eyebrow";
  ALTER TABLE "cms"."_pages_v_blocks_hero" DROP COLUMN IF EXISTS "headline";
  ALTER TABLE "cms"."_pages_v_blocks_hero" DROP COLUMN IF EXISTS "headline_accent";
  ALTER TABLE "cms"."_pages_v_blocks_hero" DROP COLUMN IF EXISTS "headline_faint";
  ALTER TABLE "cms"."_pages_v_blocks_stats_stats" DROP COLUMN IF EXISTS "label";
  ALTER TABLE "cms"."_pages_v_blocks_values_four_harmonies_items" DROP COLUMN IF EXISTS "english";
  ALTER TABLE "cms"."_pages_v_blocks_values_five_unities_items" DROP COLUMN IF EXISTS "english";
  ALTER TABLE "cms"."_pages_v_blocks_values_mottos" DROP COLUMN IF EXISTS "label";
  ALTER TABLE "cms"."_pages_v_blocks_values_mottos" DROP COLUMN IF EXISTS "english";
  ALTER TABLE "cms"."_pages_v_blocks_values" DROP COLUMN IF EXISTS "section_label";
  ALTER TABLE "cms"."_pages_v_blocks_values" DROP COLUMN IF EXISTS "headline";
  ALTER TABLE "cms"."_pages_v_blocks_about_advantages" DROP COLUMN IF EXISTS "title";
  ALTER TABLE "cms"."_pages_v_blocks_about_advantages" DROP COLUMN IF EXISTS "description";
  ALTER TABLE "cms"."_pages_v_blocks_about" DROP COLUMN IF EXISTS "section_label";
  ALTER TABLE "cms"."_pages_v_blocks_about" DROP COLUMN IF EXISTS "headline";
  ALTER TABLE "cms"."_pages_v_blocks_about" DROP COLUMN IF EXISTS "headline_accent";
  ALTER TABLE "cms"."_pages_v_blocks_about" DROP COLUMN IF EXISTS "body";
  ALTER TABLE "cms"."_pages_v_blocks_about" DROP COLUMN IF EXISTS "globe_stat_label";
  ALTER TABLE "cms"."_pages_v_blocks_services_services" DROP COLUMN IF EXISTS "title";
  ALTER TABLE "cms"."_pages_v_blocks_services_services" DROP COLUMN IF EXISTS "description";
  ALTER TABLE "cms"."_pages_v_blocks_services" DROP COLUMN IF EXISTS "section_label";
  ALTER TABLE "cms"."_pages_v_blocks_services" DROP COLUMN IF EXISTS "headline";
  ALTER TABLE "cms"."_pages_v_blocks_services" DROP COLUMN IF EXISTS "headline_accent";
  ALTER TABLE "cms"."_pages_v_blocks_platform_teaser_features" DROP COLUMN IF EXISTS "title";
  ALTER TABLE "cms"."_pages_v_blocks_platform_teaser_features" DROP COLUMN IF EXISTS "description";
  ALTER TABLE "cms"."_pages_v_blocks_platform_teaser" DROP COLUMN IF EXISTS "section_label";
  ALTER TABLE "cms"."_pages_v_blocks_platform_teaser" DROP COLUMN IF EXISTS "headline";
  ALTER TABLE "cms"."_pages_v_blocks_platform_teaser" DROP COLUMN IF EXISTS "headline_accent";
  ALTER TABLE "cms"."_pages_v_blocks_platform_teaser" DROP COLUMN IF EXISTS "body";
  ALTER TABLE "cms"."_pages_v_blocks_platform_teaser" DROP COLUMN IF EXISTS "launch_cta_label";
  ALTER TABLE "cms"."_pages_v" DROP COLUMN IF EXISTS "autosave";`)
}

export async function down({ db, payload: _payload, req: _req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "cms"."pages_blocks_hero_stats_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "cms"."pages_blocks_hero_cta_buttons_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "cms"."pages_blocks_hero_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "cms"."pages_blocks_stats_stats_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "cms"."pages_blocks_values_four_harmonies_items_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "cms"."pages_blocks_values_five_unities_items_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "cms"."pages_blocks_values_mottos_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "cms"."pages_blocks_values_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "cms"."pages_blocks_about_advantages_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "cms"."pages_blocks_about_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "cms"."pages_blocks_services_services_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "cms"."pages_blocks_services_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "cms"."pages_blocks_platform_teaser_features_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "cms"."pages_blocks_platform_teaser_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "cms"."_pages_v_blocks_hero_stats_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "cms"."_pages_v_blocks_hero_cta_buttons_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "cms"."_pages_v_blocks_hero_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "cms"."_pages_v_blocks_stats_stats_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "cms"."_pages_v_blocks_values_four_harmonies_items_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "cms"."_pages_v_blocks_values_five_unities_items_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "cms"."_pages_v_blocks_values_mottos_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "cms"."_pages_v_blocks_values_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "cms"."_pages_v_blocks_about_advantages_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "cms"."_pages_v_blocks_about_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "cms"."_pages_v_blocks_services_services_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "cms"."_pages_v_blocks_services_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "cms"."_pages_v_blocks_platform_teaser_features_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "cms"."_pages_v_blocks_platform_teaser_locales" DISABLE ROW LEVEL SECURITY;
  DROP TABLE "cms"."pages_blocks_hero_stats_locales" CASCADE;
  DROP TABLE "cms"."pages_blocks_hero_cta_buttons_locales" CASCADE;
  DROP TABLE "cms"."pages_blocks_hero_locales" CASCADE;
  DROP TABLE "cms"."pages_blocks_stats_stats_locales" CASCADE;
  DROP TABLE "cms"."pages_blocks_values_four_harmonies_items_locales" CASCADE;
  DROP TABLE "cms"."pages_blocks_values_five_unities_items_locales" CASCADE;
  DROP TABLE "cms"."pages_blocks_values_mottos_locales" CASCADE;
  DROP TABLE "cms"."pages_blocks_values_locales" CASCADE;
  DROP TABLE "cms"."pages_blocks_about_advantages_locales" CASCADE;
  DROP TABLE "cms"."pages_blocks_about_locales" CASCADE;
  DROP TABLE "cms"."pages_blocks_services_services_locales" CASCADE;
  DROP TABLE "cms"."pages_blocks_services_locales" CASCADE;
  DROP TABLE "cms"."pages_blocks_platform_teaser_features_locales" CASCADE;
  DROP TABLE "cms"."pages_blocks_platform_teaser_locales" CASCADE;
  DROP TABLE "cms"."_pages_v_blocks_hero_stats_locales" CASCADE;
  DROP TABLE "cms"."_pages_v_blocks_hero_cta_buttons_locales" CASCADE;
  DROP TABLE "cms"."_pages_v_blocks_hero_locales" CASCADE;
  DROP TABLE "cms"."_pages_v_blocks_stats_stats_locales" CASCADE;
  DROP TABLE "cms"."_pages_v_blocks_values_four_harmonies_items_locales" CASCADE;
  DROP TABLE "cms"."_pages_v_blocks_values_five_unities_items_locales" CASCADE;
  DROP TABLE "cms"."_pages_v_blocks_values_mottos_locales" CASCADE;
  DROP TABLE "cms"."_pages_v_blocks_values_locales" CASCADE;
  DROP TABLE "cms"."_pages_v_blocks_about_advantages_locales" CASCADE;
  DROP TABLE "cms"."_pages_v_blocks_about_locales" CASCADE;
  DROP TABLE "cms"."_pages_v_blocks_services_services_locales" CASCADE;
  DROP TABLE "cms"."_pages_v_blocks_services_locales" CASCADE;
  DROP TABLE "cms"."_pages_v_blocks_platform_teaser_features_locales" CASCADE;
  DROP TABLE "cms"."_pages_v_blocks_platform_teaser_locales" CASCADE;
  DROP INDEX "cms"."_pages_v_snapshot_idx";
  DROP INDEX "cms"."_pages_v_published_locale_idx";
  ALTER TABLE "cms"."pages_blocks_hero_stats" ADD COLUMN "label" varchar;
  ALTER TABLE "cms"."pages_blocks_hero_cta_buttons" ADD COLUMN "label" varchar;
  ALTER TABLE "cms"."pages_blocks_hero" ADD COLUMN "eyebrow" varchar;
  ALTER TABLE "cms"."pages_blocks_hero" ADD COLUMN "headline" varchar;
  ALTER TABLE "cms"."pages_blocks_hero" ADD COLUMN "headline_accent" varchar;
  ALTER TABLE "cms"."pages_blocks_hero" ADD COLUMN "headline_faint" varchar;
  ALTER TABLE "cms"."pages_blocks_stats_stats" ADD COLUMN "label" varchar;
  ALTER TABLE "cms"."pages_blocks_values_four_harmonies_items" ADD COLUMN "english" varchar;
  ALTER TABLE "cms"."pages_blocks_values_five_unities_items" ADD COLUMN "english" varchar;
  ALTER TABLE "cms"."pages_blocks_values_mottos" ADD COLUMN "label" varchar;
  ALTER TABLE "cms"."pages_blocks_values_mottos" ADD COLUMN "english" varchar;
  ALTER TABLE "cms"."pages_blocks_values" ADD COLUMN "section_label" varchar;
  ALTER TABLE "cms"."pages_blocks_values" ADD COLUMN "headline" varchar;
  ALTER TABLE "cms"."pages_blocks_about_advantages" ADD COLUMN "title" varchar;
  ALTER TABLE "cms"."pages_blocks_about_advantages" ADD COLUMN "description" varchar;
  ALTER TABLE "cms"."pages_blocks_about" ADD COLUMN "section_label" varchar;
  ALTER TABLE "cms"."pages_blocks_about" ADD COLUMN "headline" varchar;
  ALTER TABLE "cms"."pages_blocks_about" ADD COLUMN "headline_accent" varchar;
  ALTER TABLE "cms"."pages_blocks_about" ADD COLUMN "body" jsonb;
  ALTER TABLE "cms"."pages_blocks_about" ADD COLUMN "globe_stat_label" varchar;
  ALTER TABLE "cms"."pages_blocks_services_services" ADD COLUMN "title" varchar;
  ALTER TABLE "cms"."pages_blocks_services_services" ADD COLUMN "description" varchar;
  ALTER TABLE "cms"."pages_blocks_services" ADD COLUMN "section_label" varchar;
  ALTER TABLE "cms"."pages_blocks_services" ADD COLUMN "headline" varchar;
  ALTER TABLE "cms"."pages_blocks_services" ADD COLUMN "headline_accent" varchar;
  ALTER TABLE "cms"."pages_blocks_platform_teaser_features" ADD COLUMN "title" varchar;
  ALTER TABLE "cms"."pages_blocks_platform_teaser_features" ADD COLUMN "description" varchar;
  ALTER TABLE "cms"."pages_blocks_platform_teaser" ADD COLUMN "section_label" varchar;
  ALTER TABLE "cms"."pages_blocks_platform_teaser" ADD COLUMN "headline" varchar;
  ALTER TABLE "cms"."pages_blocks_platform_teaser" ADD COLUMN "headline_accent" varchar;
  ALTER TABLE "cms"."pages_blocks_platform_teaser" ADD COLUMN "body" jsonb;
  ALTER TABLE "cms"."pages_blocks_platform_teaser" ADD COLUMN "launch_cta_label" varchar;
  ALTER TABLE "cms"."_pages_v_blocks_hero_stats" ADD COLUMN "label" varchar;
  ALTER TABLE "cms"."_pages_v_blocks_hero_cta_buttons" ADD COLUMN "label" varchar;
  ALTER TABLE "cms"."_pages_v_blocks_hero" ADD COLUMN "eyebrow" varchar;
  ALTER TABLE "cms"."_pages_v_blocks_hero" ADD COLUMN "headline" varchar;
  ALTER TABLE "cms"."_pages_v_blocks_hero" ADD COLUMN "headline_accent" varchar;
  ALTER TABLE "cms"."_pages_v_blocks_hero" ADD COLUMN "headline_faint" varchar;
  ALTER TABLE "cms"."_pages_v_blocks_stats_stats" ADD COLUMN "label" varchar;
  ALTER TABLE "cms"."_pages_v_blocks_values_four_harmonies_items" ADD COLUMN "english" varchar;
  ALTER TABLE "cms"."_pages_v_blocks_values_five_unities_items" ADD COLUMN "english" varchar;
  ALTER TABLE "cms"."_pages_v_blocks_values_mottos" ADD COLUMN "label" varchar;
  ALTER TABLE "cms"."_pages_v_blocks_values_mottos" ADD COLUMN "english" varchar;
  ALTER TABLE "cms"."_pages_v_blocks_values" ADD COLUMN "section_label" varchar;
  ALTER TABLE "cms"."_pages_v_blocks_values" ADD COLUMN "headline" varchar;
  ALTER TABLE "cms"."_pages_v_blocks_about_advantages" ADD COLUMN "title" varchar;
  ALTER TABLE "cms"."_pages_v_blocks_about_advantages" ADD COLUMN "description" varchar;
  ALTER TABLE "cms"."_pages_v_blocks_about" ADD COLUMN "section_label" varchar;
  ALTER TABLE "cms"."_pages_v_blocks_about" ADD COLUMN "headline" varchar;
  ALTER TABLE "cms"."_pages_v_blocks_about" ADD COLUMN "headline_accent" varchar;
  ALTER TABLE "cms"."_pages_v_blocks_about" ADD COLUMN "body" jsonb;
  ALTER TABLE "cms"."_pages_v_blocks_about" ADD COLUMN "globe_stat_label" varchar;
  ALTER TABLE "cms"."_pages_v_blocks_services_services" ADD COLUMN "title" varchar;
  ALTER TABLE "cms"."_pages_v_blocks_services_services" ADD COLUMN "description" varchar;
  ALTER TABLE "cms"."_pages_v_blocks_services" ADD COLUMN "section_label" varchar;
  ALTER TABLE "cms"."_pages_v_blocks_services" ADD COLUMN "headline" varchar;
  ALTER TABLE "cms"."_pages_v_blocks_services" ADD COLUMN "headline_accent" varchar;
  ALTER TABLE "cms"."_pages_v_blocks_platform_teaser_features" ADD COLUMN "title" varchar;
  ALTER TABLE "cms"."_pages_v_blocks_platform_teaser_features" ADD COLUMN "description" varchar;
  ALTER TABLE "cms"."_pages_v_blocks_platform_teaser" ADD COLUMN "section_label" varchar;
  ALTER TABLE "cms"."_pages_v_blocks_platform_teaser" ADD COLUMN "headline" varchar;
  ALTER TABLE "cms"."_pages_v_blocks_platform_teaser" ADD COLUMN "headline_accent" varchar;
  ALTER TABLE "cms"."_pages_v_blocks_platform_teaser" ADD COLUMN "body" jsonb;
  ALTER TABLE "cms"."_pages_v_blocks_platform_teaser" ADD COLUMN "launch_cta_label" varchar;
  ALTER TABLE "cms"."_pages_v" ADD COLUMN "autosave" boolean;
  CREATE INDEX "_pages_v_autosave_idx" ON "cms"."_pages_v" USING btree ("autosave");
  ALTER TABLE "cms"."_pages_v" DROP COLUMN IF EXISTS "snapshot";
  ALTER TABLE "cms"."_pages_v" DROP COLUMN IF EXISTS "published_locale";
  ALTER TABLE "cms"."platform_settings" DROP COLUMN IF EXISTS "contact_modal_heading";
  ALTER TABLE "cms"."platform_settings" DROP COLUMN IF EXISTS "contact_modal_success_title";
  ALTER TABLE "cms"."platform_settings" DROP COLUMN IF EXISTS "contact_modal_success_message";
  ALTER TABLE "cms"."platform_settings" DROP COLUMN IF EXISTS "detail_label_size";
  ALTER TABLE "cms"."platform_settings" DROP COLUMN IF EXISTS "detail_label_zone";
  ALTER TABLE "cms"."platform_settings" DROP COLUMN IF EXISTS "detail_label_setup";
  ALTER TABLE "cms"."platform_settings" DROP COLUMN IF EXISTS "detail_label_lease";
  ALTER TABLE "cms"."platform_settings" DROP COLUMN IF EXISTS "detail_label_price";
  ALTER TABLE "cms"."platform_settings" DROP COLUMN IF EXISTS "requirement_modal_heading";
  ALTER TABLE "cms"."platform_settings" DROP COLUMN IF EXISTS "requirement_modal_description";
  ALTER TABLE "cms"."platform_settings" DROP COLUMN IF EXISTS "requirement_modal_success_title";
  ALTER TABLE "cms"."platform_settings" DROP COLUMN IF EXISTS "requirement_modal_success_message";
  DROP TYPE "cms"."_locales";
  DROP TYPE "cms"."enum__pages_v_published_locale";`)
}
