import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

/**
 * Phase 5b.2 — additive schema migration.
 *
 * Adds:
 *   • 5 new globals (all-localized): nav_settings, footer_settings, weconnect_settings,
 *     requirement_form_settings, contact_form_settings — each with a parent table
 *     (id serial) and a *_locales table (varchar columns + _locale + _parent_id).
 *   • 3 new array fields on existing blocks:
 *       AboutBlock.milestones        → year (text), title (localized)
 *       ClientsBlock.partner_types   → icon (enum), title + examples (localized)
 *       ClientsBlock.regions         → count (text), name (localized)
 *     Plus matching `_pages_v_*` version tables (drafts).
 *   • Localized columns on existing block locales:
 *       pages_blocks_hero_locales.scroll_hint_label
 *       pages_blocks_services_locales.subtitle
 *       pages_blocks_clients_locales.network_subtitle, regions_heading
 *       (and matching _pages_v_blocks_*_locales)
 *   • A NEW pages_blocks_clients_locales table (didn't exist before — clients block
 *     had no localized parent fields until 5b.2).
 *
 * Pre-population:
 *   ALL fields are pre-populated in this migration (decision: 2026-05-06).
 *   Reason: components must read from a populated CMS BEFORE the hardcoded JS
 *   arrays are deleted in Phase 5b.3. If we deferred pre-population to 5b.4,
 *   any 5b.3c deploy would render empty timelines/partner grids until the
 *   translation fill ran.
 *
 *   Sources for pre-population:
 *     • Globals (5)         → EN + ZH from src/lib/i18n/strings.ts dictionary
 *     • milestones (4)      → from hardcoded array in AboutBlock.tsx
 *     • partnerTypes (4)    → from hardcoded array in ClientsBlock.tsx
 *     • regions (6)         → from hardcoded array in ClientsBlock.tsx
 *     • clients_locales     → networkSubtitle/regionsHeading new EN + existing ZH
 *     • hero scroll_hint    → SCROLL / 向下滚动
 *     • services subtitle   → from existing hardcoded JSX
 *
 *   Some `examples` strings on partnerTypes are AI-translated EN→ZH (the
 *   original codebase only had EN values for those). Phase 5b.4's SQL refinement
 *   pass is where owner reviews wording.
 *
 * NOTE: This migration was hand-written (not auto-generated by `payload
 * migrate:create`) because the CLI is currently broken on this dev box under
 * Node v24 + tsx 4.21 — see docs/improvements/infrastructure/cms-backup-runbook.md
 * for details. The migration follows Drizzle/Payload's table-naming conventions
 * exactly as observed in prior migrations.
 */
export async function up({ db, payload: _payload, req: _req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
    -- ── 1. Enum for ClientsBlock.partnerTypes.icon ──────────────────────────
    DO $$ BEGIN
      CREATE TYPE "cms"."enum_pages_blocks_clients_partner_types_icon" AS ENUM('Globe', 'Building2', 'Handshake', 'Award');
    EXCEPTION WHEN duplicate_object THEN null; END $$;

    DO $$ BEGIN
      CREATE TYPE "cms"."enum__pages_v_blocks_clients_partner_types_icon" AS ENUM('Globe', 'Building2', 'Handshake', 'Award');
    EXCEPTION WHEN duplicate_object THEN null; END $$;

    -- ── 2. New global parent tables (singletons) ────────────────────────────
    CREATE TABLE IF NOT EXISTS "cms"."nav_settings" (
      "id" serial PRIMARY KEY NOT NULL,
      "updated_at" timestamp(3) with time zone,
      "created_at" timestamp(3) with time zone
    );

    CREATE TABLE IF NOT EXISTS "cms"."footer_settings" (
      "id" serial PRIMARY KEY NOT NULL,
      "updated_at" timestamp(3) with time zone,
      "created_at" timestamp(3) with time zone
    );

    CREATE TABLE IF NOT EXISTS "cms"."weconnect_settings" (
      "id" serial PRIMARY KEY NOT NULL,
      "updated_at" timestamp(3) with time zone,
      "created_at" timestamp(3) with time zone
    );

    CREATE TABLE IF NOT EXISTS "cms"."requirement_form_settings" (
      "id" serial PRIMARY KEY NOT NULL,
      "updated_at" timestamp(3) with time zone,
      "created_at" timestamp(3) with time zone
    );

    CREATE TABLE IF NOT EXISTS "cms"."contact_form_settings" (
      "id" serial PRIMARY KEY NOT NULL,
      "updated_at" timestamp(3) with time zone,
      "created_at" timestamp(3) with time zone
    );

    -- ── 3. New global locales tables ────────────────────────────────────────
    CREATE TABLE IF NOT EXISTS "cms"."nav_settings_locales" (
      "link_philosophy" varchar,
      "link_about" varchar,
      "link_services" varchar,
      "link_partners" varchar,
      "weconnect_label" varchar,
      "weconnect_cta" varchar,
      "language_toggle_aria" varchar,
      "id" serial PRIMARY KEY NOT NULL,
      "_locale" "cms"."_locales" NOT NULL,
      "_parent_id" integer NOT NULL
    );

    CREATE TABLE IF NOT EXISTS "cms"."footer_settings_locales" (
      "tagline" varchar,
      "mission" varchar,
      "pillar_line" varchar,
      "e_harbor_tag" varchar,
      "copyright" varchar,
      "id" serial PRIMARY KEY NOT NULL,
      "_locale" "cms"."_locales" NOT NULL,
      "_parent_id" integer NOT NULL
    );

    CREATE TABLE IF NOT EXISTS "cms"."weconnect_settings_locales" (
      "tab_needs" varchar,
      "tab_alerts" varchar,
      "tab_profile" varchar,
      "post_need" varchar,
      "post_need_accent" varchar,
      "post_need_description" varchar,
      "share_offering" varchar,
      "share_offering_accent" varchar,
      "share_offering_description" varchar,
      "recent_needs" varchar,
      "advisory_alerts" varchar,
      "preview_label" varchar,
      "coming_soon_label" varchar,
      "profile_member" varchar,
      "profile_member_since" varchar,
      "my_posts" varchar,
      "company_profile" varchar,
      "enterprise_user" varchar,
      "enterprise_role" varchar,
      "settings_heading" varchar,
      "setting_language" varchar,
      "setting_notifications" varchar,
      "setting_contact_pg" varchar,
      "setting_about" varchar,
      "id" serial PRIMARY KEY NOT NULL,
      "_locale" "cms"."_locales" NOT NULL,
      "_parent_id" integer NOT NULL
    );

    CREATE TABLE IF NOT EXISTS "cms"."requirement_form_settings_locales" (
      "heading" varchar,
      "description" varchar,
      "required_hint" varchar,
      "response_sla" varchar,
      "section_basic" varchar,
      "section_requirement" varchar,
      "section_commercial" varchar,
      "section_contact" varchar,
      "label_subject" varchar,
      "label_inquiry_type" varchar,
      "label_description" varchar,
      "label_goal" varchar,
      "label_target_location" varchar,
      "label_budget" varchar,
      "label_timeline" varchar,
      "label_full_name" varchar,
      "label_job_title" varchar,
      "label_company" varchar,
      "label_email" varchar,
      "label_phone" varchar,
      "label_message" varchar,
      "placeholder_subject" varchar,
      "placeholder_description" varchar,
      "placeholder_goal" varchar,
      "placeholder_target_location" varchar,
      "placeholder_budget" varchar,
      "placeholder_name" varchar,
      "placeholder_title" varchar,
      "placeholder_company" varchar,
      "placeholder_email" varchar,
      "placeholder_phone" varchar,
      "placeholder_message" varchar,
      "button_submit" varchar,
      "button_submitting" varchar,
      "success_title" varchar,
      "success_message" varchar,
      "error_required" varchar,
      "error_invalid_email" varchar,
      "error_generic" varchar,
      "type_office" varchar,
      "type_lab" varchar,
      "type_factory" varchar,
      "type_funding" varchar,
      "type_market_entry" varchar,
      "type_other" varchar,
      "timeline_select" varchar,
      "timeline_urgent" varchar,
      "timeline_this_quarter" varchar,
      "timeline3to6" varchar,
      "timeline_exploring" varchar,
      "id" serial PRIMARY KEY NOT NULL,
      "_locale" "cms"."_locales" NOT NULL,
      "_parent_id" integer NOT NULL
    );

    CREATE TABLE IF NOT EXISTS "cms"."contact_form_settings_locales" (
      "heading" varchar,
      "success_title" varchar,
      "success_message" varchar,
      "button_send_intro" varchar,
      "button_sending" varchar,
      "detail_label_size" varchar,
      "detail_label_zone" varchar,
      "detail_label_setup" varchar,
      "detail_label_lease" varchar,
      "detail_label_price" varchar,
      "id" serial PRIMARY KEY NOT NULL,
      "_locale" "cms"."_locales" NOT NULL,
      "_parent_id" integer NOT NULL
    );

    -- ── 4. New array tables on existing blocks (LIVE) ───────────────────────
    -- AboutBlock.milestones
    CREATE TABLE IF NOT EXISTS "cms"."pages_blocks_about_milestones" (
      "_order" integer NOT NULL,
      "_parent_id" varchar NOT NULL,
      "id" varchar PRIMARY KEY NOT NULL,
      "year" varchar NOT NULL
    );

    CREATE TABLE IF NOT EXISTS "cms"."pages_blocks_about_milestones_locales" (
      "title" varchar,
      "id" serial PRIMARY KEY NOT NULL,
      "_locale" "cms"."_locales" NOT NULL,
      "_parent_id" varchar NOT NULL
    );

    -- ClientsBlock.partnerTypes
    CREATE TABLE IF NOT EXISTS "cms"."pages_blocks_clients_partner_types" (
      "_order" integer NOT NULL,
      "_parent_id" varchar NOT NULL,
      "id" varchar PRIMARY KEY NOT NULL,
      "icon" "cms"."enum_pages_blocks_clients_partner_types_icon" NOT NULL
    );

    CREATE TABLE IF NOT EXISTS "cms"."pages_blocks_clients_partner_types_locales" (
      "title" varchar,
      "examples" varchar,
      "id" serial PRIMARY KEY NOT NULL,
      "_locale" "cms"."_locales" NOT NULL,
      "_parent_id" varchar NOT NULL
    );

    -- ClientsBlock.regions
    CREATE TABLE IF NOT EXISTS "cms"."pages_blocks_clients_regions" (
      "_order" integer NOT NULL,
      "_parent_id" varchar NOT NULL,
      "id" varchar PRIMARY KEY NOT NULL,
      "count" varchar NOT NULL
    );

    CREATE TABLE IF NOT EXISTS "cms"."pages_blocks_clients_regions_locales" (
      "name" varchar,
      "id" serial PRIMARY KEY NOT NULL,
      "_locale" "cms"."_locales" NOT NULL,
      "_parent_id" varchar NOT NULL
    );

    -- ClientsBlock parent locales (didn't exist before — Clients had no localized
    -- parent fields prior to 5b.2)
    CREATE TABLE IF NOT EXISTS "cms"."pages_blocks_clients_locales" (
      "network_subtitle" varchar,
      "regions_heading" varchar,
      "id" serial PRIMARY KEY NOT NULL,
      "_locale" "cms"."_locales" NOT NULL,
      "_parent_id" varchar NOT NULL
    );

    -- ── 5. New array tables on existing blocks (VERSIONS / drafts) ──────────
    CREATE TABLE IF NOT EXISTS "cms"."_pages_v_blocks_about_milestones" (
      "_order" integer NOT NULL,
      "_parent_id" integer NOT NULL,
      "id" serial PRIMARY KEY NOT NULL,
      "year" varchar,
      "_uuid" varchar
    );

    CREATE TABLE IF NOT EXISTS "cms"."_pages_v_blocks_about_milestones_locales" (
      "title" varchar,
      "id" serial PRIMARY KEY NOT NULL,
      "_locale" "cms"."_locales" NOT NULL,
      "_parent_id" integer NOT NULL
    );

    CREATE TABLE IF NOT EXISTS "cms"."_pages_v_blocks_clients_partner_types" (
      "_order" integer NOT NULL,
      "_parent_id" integer NOT NULL,
      "id" serial PRIMARY KEY NOT NULL,
      "icon" "cms"."enum__pages_v_blocks_clients_partner_types_icon",
      "_uuid" varchar
    );

    CREATE TABLE IF NOT EXISTS "cms"."_pages_v_blocks_clients_partner_types_locales" (
      "title" varchar,
      "examples" varchar,
      "id" serial PRIMARY KEY NOT NULL,
      "_locale" "cms"."_locales" NOT NULL,
      "_parent_id" integer NOT NULL
    );

    CREATE TABLE IF NOT EXISTS "cms"."_pages_v_blocks_clients_regions" (
      "_order" integer NOT NULL,
      "_parent_id" integer NOT NULL,
      "id" serial PRIMARY KEY NOT NULL,
      "count" varchar,
      "_uuid" varchar
    );

    CREATE TABLE IF NOT EXISTS "cms"."_pages_v_blocks_clients_regions_locales" (
      "name" varchar,
      "id" serial PRIMARY KEY NOT NULL,
      "_locale" "cms"."_locales" NOT NULL,
      "_parent_id" integer NOT NULL
    );

    CREATE TABLE IF NOT EXISTS "cms"."_pages_v_blocks_clients_locales" (
      "network_subtitle" varchar,
      "regions_heading" varchar,
      "id" serial PRIMARY KEY NOT NULL,
      "_locale" "cms"."_locales" NOT NULL,
      "_parent_id" integer NOT NULL
    );

    -- ── 6. ALTERs on existing locale tables ─────────────────────────────────
    ALTER TABLE "cms"."pages_blocks_hero_locales" ADD COLUMN IF NOT EXISTS "scroll_hint_label" varchar;
    ALTER TABLE "cms"."_pages_v_blocks_hero_locales" ADD COLUMN IF NOT EXISTS "scroll_hint_label" varchar;
    ALTER TABLE "cms"."pages_blocks_services_locales" ADD COLUMN IF NOT EXISTS "subtitle" varchar;
    ALTER TABLE "cms"."_pages_v_blocks_services_locales" ADD COLUMN IF NOT EXISTS "subtitle" varchar;

    -- ── 7. FK constraints ───────────────────────────────────────────────────
    -- Globals: locales → parent
    ALTER TABLE "cms"."nav_settings_locales" ADD CONSTRAINT "nav_settings_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "cms"."nav_settings"("id") ON DELETE cascade ON UPDATE no action;
    ALTER TABLE "cms"."footer_settings_locales" ADD CONSTRAINT "footer_settings_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "cms"."footer_settings"("id") ON DELETE cascade ON UPDATE no action;
    ALTER TABLE "cms"."weconnect_settings_locales" ADD CONSTRAINT "weconnect_settings_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "cms"."weconnect_settings"("id") ON DELETE cascade ON UPDATE no action;
    ALTER TABLE "cms"."requirement_form_settings_locales" ADD CONSTRAINT "requirement_form_settings_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "cms"."requirement_form_settings"("id") ON DELETE cascade ON UPDATE no action;
    ALTER TABLE "cms"."contact_form_settings_locales" ADD CONSTRAINT "contact_form_settings_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "cms"."contact_form_settings"("id") ON DELETE cascade ON UPDATE no action;

    -- Block arrays (live): item → block, item_locales → item
    ALTER TABLE "cms"."pages_blocks_about_milestones" ADD CONSTRAINT "pages_blocks_about_milestones_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "cms"."pages_blocks_about"("id") ON DELETE cascade ON UPDATE no action;
    ALTER TABLE "cms"."pages_blocks_about_milestones_locales" ADD CONSTRAINT "pages_blocks_about_milestones_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "cms"."pages_blocks_about_milestones"("id") ON DELETE cascade ON UPDATE no action;
    ALTER TABLE "cms"."pages_blocks_clients_partner_types" ADD CONSTRAINT "pages_blocks_clients_partner_types_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "cms"."pages_blocks_clients"("id") ON DELETE cascade ON UPDATE no action;
    ALTER TABLE "cms"."pages_blocks_clients_partner_types_locales" ADD CONSTRAINT "pages_blocks_clients_partner_types_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "cms"."pages_blocks_clients_partner_types"("id") ON DELETE cascade ON UPDATE no action;
    ALTER TABLE "cms"."pages_blocks_clients_regions" ADD CONSTRAINT "pages_blocks_clients_regions_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "cms"."pages_blocks_clients"("id") ON DELETE cascade ON UPDATE no action;
    ALTER TABLE "cms"."pages_blocks_clients_regions_locales" ADD CONSTRAINT "pages_blocks_clients_regions_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "cms"."pages_blocks_clients_regions"("id") ON DELETE cascade ON UPDATE no action;
    ALTER TABLE "cms"."pages_blocks_clients_locales" ADD CONSTRAINT "pages_blocks_clients_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "cms"."pages_blocks_clients"("id") ON DELETE cascade ON UPDATE no action;

    -- Block arrays (versions): item → versioned block
    ALTER TABLE "cms"."_pages_v_blocks_about_milestones" ADD CONSTRAINT "_pages_v_blocks_about_milestones_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "cms"."_pages_v_blocks_about"("id") ON DELETE cascade ON UPDATE no action;
    ALTER TABLE "cms"."_pages_v_blocks_about_milestones_locales" ADD CONSTRAINT "_pages_v_blocks_about_milestones_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "cms"."_pages_v_blocks_about_milestones"("id") ON DELETE cascade ON UPDATE no action;
    ALTER TABLE "cms"."_pages_v_blocks_clients_partner_types" ADD CONSTRAINT "_pages_v_blocks_clients_partner_types_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "cms"."_pages_v_blocks_clients"("id") ON DELETE cascade ON UPDATE no action;
    ALTER TABLE "cms"."_pages_v_blocks_clients_partner_types_locales" ADD CONSTRAINT "_pages_v_blocks_clients_partner_types_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "cms"."_pages_v_blocks_clients_partner_types"("id") ON DELETE cascade ON UPDATE no action;
    ALTER TABLE "cms"."_pages_v_blocks_clients_regions" ADD CONSTRAINT "_pages_v_blocks_clients_regions_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "cms"."_pages_v_blocks_clients"("id") ON DELETE cascade ON UPDATE no action;
    ALTER TABLE "cms"."_pages_v_blocks_clients_regions_locales" ADD CONSTRAINT "_pages_v_blocks_clients_regions_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "cms"."_pages_v_blocks_clients_regions"("id") ON DELETE cascade ON UPDATE no action;
    ALTER TABLE "cms"."_pages_v_blocks_clients_locales" ADD CONSTRAINT "_pages_v_blocks_clients_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "cms"."_pages_v_blocks_clients"("id") ON DELETE cascade ON UPDATE no action;

    -- ── 8. Indexes ───────────────────────────────────────────────────────────
    -- Globals: unique (_locale, _parent_id) on locales tables
    CREATE UNIQUE INDEX IF NOT EXISTS "nav_settings_locales_locale_parent_id_unique" ON "cms"."nav_settings_locales" USING btree ("_locale","_parent_id");
    CREATE UNIQUE INDEX IF NOT EXISTS "footer_settings_locales_locale_parent_id_unique" ON "cms"."footer_settings_locales" USING btree ("_locale","_parent_id");
    CREATE UNIQUE INDEX IF NOT EXISTS "weconnect_settings_locales_locale_parent_id_unique" ON "cms"."weconnect_settings_locales" USING btree ("_locale","_parent_id");
    CREATE UNIQUE INDEX IF NOT EXISTS "requirement_form_settings_locales_locale_parent_id_unique" ON "cms"."requirement_form_settings_locales" USING btree ("_locale","_parent_id");
    CREATE UNIQUE INDEX IF NOT EXISTS "contact_form_settings_locales_locale_parent_id_unique" ON "cms"."contact_form_settings_locales" USING btree ("_locale","_parent_id");

    -- Block array: order + parent_id indexes
    CREATE INDEX IF NOT EXISTS "pages_blocks_about_milestones_order_idx" ON "cms"."pages_blocks_about_milestones" USING btree ("_order");
    CREATE INDEX IF NOT EXISTS "pages_blocks_about_milestones_parent_id_idx" ON "cms"."pages_blocks_about_milestones" USING btree ("_parent_id");
    CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_about_milestones_locales_locale_parent_id_uniqu" ON "cms"."pages_blocks_about_milestones_locales" USING btree ("_locale","_parent_id");

    CREATE INDEX IF NOT EXISTS "pages_blocks_clients_partner_types_order_idx" ON "cms"."pages_blocks_clients_partner_types" USING btree ("_order");
    CREATE INDEX IF NOT EXISTS "pages_blocks_clients_partner_types_parent_id_idx" ON "cms"."pages_blocks_clients_partner_types" USING btree ("_parent_id");
    CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_clients_partner_types_locales_locale_parent_id_" ON "cms"."pages_blocks_clients_partner_types_locales" USING btree ("_locale","_parent_id");

    CREATE INDEX IF NOT EXISTS "pages_blocks_clients_regions_order_idx" ON "cms"."pages_blocks_clients_regions" USING btree ("_order");
    CREATE INDEX IF NOT EXISTS "pages_blocks_clients_regions_parent_id_idx" ON "cms"."pages_blocks_clients_regions" USING btree ("_parent_id");
    CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_clients_regions_locales_locale_parent_id_unique" ON "cms"."pages_blocks_clients_regions_locales" USING btree ("_locale","_parent_id");

    CREATE UNIQUE INDEX IF NOT EXISTS "pages_blocks_clients_locales_locale_parent_id_unique" ON "cms"."pages_blocks_clients_locales" USING btree ("_locale","_parent_id");

    -- Versions: same indexes on _pages_v_*
    CREATE INDEX IF NOT EXISTS "_pages_v_blocks_about_milestones_order_idx" ON "cms"."_pages_v_blocks_about_milestones" USING btree ("_order");
    CREATE INDEX IF NOT EXISTS "_pages_v_blocks_about_milestones_parent_id_idx" ON "cms"."_pages_v_blocks_about_milestones" USING btree ("_parent_id");
    CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_about_milestones_locales_locale_parent_id_un" ON "cms"."_pages_v_blocks_about_milestones_locales" USING btree ("_locale","_parent_id");
    CREATE INDEX IF NOT EXISTS "_pages_v_blocks_clients_partner_types_order_idx" ON "cms"."_pages_v_blocks_clients_partner_types" USING btree ("_order");
    CREATE INDEX IF NOT EXISTS "_pages_v_blocks_clients_partner_types_parent_id_idx" ON "cms"."_pages_v_blocks_clients_partner_types" USING btree ("_parent_id");
    CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_clients_partner_types_locales_locale_parent_" ON "cms"."_pages_v_blocks_clients_partner_types_locales" USING btree ("_locale","_parent_id");
    CREATE INDEX IF NOT EXISTS "_pages_v_blocks_clients_regions_order_idx" ON "cms"."_pages_v_blocks_clients_regions" USING btree ("_order");
    CREATE INDEX IF NOT EXISTS "_pages_v_blocks_clients_regions_parent_id_idx" ON "cms"."_pages_v_blocks_clients_regions" USING btree ("_parent_id");
    CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_clients_regions_locales_locale_parent_id_uni" ON "cms"."_pages_v_blocks_clients_regions_locales" USING btree ("_locale","_parent_id");
    CREATE UNIQUE INDEX IF NOT EXISTS "_pages_v_blocks_clients_locales_locale_parent_id_unique" ON "cms"."_pages_v_blocks_clients_locales" USING btree ("_locale","_parent_id");

    -- ── 9. Pre-populate global singletons ───────────────────────────────────
    -- Each global gets one parent row + two locales rows (en, zh).
    INSERT INTO "cms"."nav_settings" ("id", "updated_at", "created_at")
      SELECT 1, now(), now()
      WHERE NOT EXISTS (SELECT 1 FROM "cms"."nav_settings" WHERE id = 1);
    INSERT INTO "cms"."nav_settings_locales" ("_locale", "_parent_id", "link_philosophy", "link_about", "link_services", "link_partners", "weconnect_label", "weconnect_cta", "language_toggle_aria")
    VALUES
      ('en', 1, 'Philosophy', 'About', 'Services', 'Partners', 'WeConnect ✦', 'WECONNECT PLATFORM →', 'Switch language'),
      ('zh', 1, '理念', '关于我们', '服务', '合作伙伴', 'WeConnect ✦', 'WECONNECT 平台 →', '切换语言')
    ON CONFLICT ("_locale", "_parent_id") DO NOTHING;

    INSERT INTO "cms"."footer_settings" ("id", "updated_at", "created_at")
      SELECT 1, now(), now()
      WHERE NOT EXISTS (SELECT 1 FROM "cms"."footer_settings" WHERE id = 1);
    INSERT INTO "cms"."footer_settings_locales" ("_locale", "_parent_id", "tagline", "mission", "pillar_line", "e_harbor_tag", "copyright")
    VALUES
      ('en', 1, 'A globalized tech innovation ecosystem.', 'Making innovation open to anyone, anywhere.', 'Tech Innovation · Business Empowerment · Human Care', 'by E-Harbor', '© 2026 E-Harbor / PER GROUP · Singapore'),
      ('zh', 1, '全球化的科技创新生态平台。', '让创新对任何人、任何地方开放。', '科技创新 · 商业赋能 · 人文关怀', 'E-Harbor 出品', '© 2026 E-Harbor / PER GROUP · 新加坡')
    ON CONFLICT ("_locale", "_parent_id") DO NOTHING;

    INSERT INTO "cms"."weconnect_settings" ("id", "updated_at", "created_at")
      SELECT 1, now(), now()
      WHERE NOT EXISTS (SELECT 1 FROM "cms"."weconnect_settings" WHERE id = 1);
    INSERT INTO "cms"."weconnect_settings_locales" ("_locale", "_parent_id",
      "tab_needs", "tab_alerts", "tab_profile",
      "post_need", "post_need_accent", "post_need_description",
      "share_offering", "share_offering_accent", "share_offering_description",
      "recent_needs", "advisory_alerts", "preview_label", "coming_soon_label",
      "profile_member", "profile_member_since", "my_posts", "company_profile",
      "enterprise_user", "enterprise_role",
      "settings_heading", "setting_language", "setting_notifications", "setting_contact_pg", "setting_about")
    VALUES
      ('en', 1,
        'Needs', 'Alerts', 'Profile',
        'Post a Need', 'Need', 'Tell us what you''re looking for.',
        'Share What You Offer', 'Offer', 'Let us know your capabilities.',
        'Recent Needs', 'Advisory Alerts', 'Preview', 'Coming Soon',
        'PER GROUP Enterprise', 'E-Harbor Member since 2024', 'My Posts', 'Company Profile',
        'PER GROUP User', 'Enterprise Member',
        'Settings', 'Language', 'Notification preferences', 'Contact PER GROUP', 'About WeConnect'),
      ('zh', 1,
        '需求', '资讯', '我的',
        '发布需求', '需求', '告诉我们您在寻找什么。',
        '分享您的能力', '能力', '让我们了解您的能力。',
        '最新需求', '顾问预警', '示例预览', '即将上线',
        'PER GROUP 企业会员', 'E-Harbor会员，2024年起', '我的发布', '公司档案',
        'PER GROUP 用户', '企业会员',
        '设置', '语言', '通知设置', '联系 PER GROUP', '关于 WeConnect')
    ON CONFLICT ("_locale", "_parent_id") DO NOTHING;

    INSERT INTO "cms"."requirement_form_settings" ("id", "updated_at", "created_at")
      SELECT 1, now(), now()
      WHERE NOT EXISTS (SELECT 1 FROM "cms"."requirement_form_settings" WHERE id = 1);
    INSERT INTO "cms"."requirement_form_settings_locales" ("_locale", "_parent_id",
      "heading", "description", "required_hint", "response_sla",
      "section_basic", "section_requirement", "section_commercial", "section_contact",
      "label_subject", "label_inquiry_type", "label_description", "label_goal",
      "label_target_location", "label_budget", "label_timeline",
      "label_full_name", "label_job_title", "label_company",
      "label_email", "label_phone", "label_message",
      "placeholder_subject", "placeholder_description", "placeholder_goal",
      "placeholder_target_location", "placeholder_budget",
      "placeholder_name", "placeholder_title", "placeholder_company",
      "placeholder_email", "placeholder_phone", "placeholder_message",
      "button_submit", "button_submitting",
      "success_title", "success_message",
      "error_required", "error_invalid_email", "error_generic",
      "type_office", "type_lab", "type_factory", "type_funding", "type_market_entry", "type_other",
      "timeline_select", "timeline_urgent", "timeline_this_quarter", "timeline3to6", "timeline_exploring")
    VALUES
      ('en', 1,
        'Post a Requirement', 'Tell the WeConnect network what you need',
        'Required fields are marked with', 'PER GROUP will respond within 1 business day',
        'Basic Information', 'Requirement Details', 'Commercial Parameters', 'Contact Information',
        'Subject', 'Inquiry Type', 'Description', 'Goal / Objective',
        'Target Location', 'Budget', 'Timeline',
        'Full Name', 'Job Title', 'Company',
        'Email', 'Phone', 'Message',
        'Brief title for your inquiry', 'Describe what you''re looking for', 'What does success look like?',
        'e.g. Singapore, Vietnam, EU', 'e.g. SGD 5k–15k/mo',
        'Your name', 'e.g. Director', 'Company name',
        'your@email.com', '+65 xxxx xxxx', 'Tell us a bit about what you''re looking for',
        'Submit Requirement', 'Submitting…',
        'Got it — we''ll be in touch.', 'PER GROUP will respond within 1 business day.',
        'Required', 'Invalid email', 'Please fill in the required fields.',
        '🏢 Office Space', '🔬 Lab / R&D Space', '🏭 Factory / Industrial Land', '💰 Investment / Funding', '🌏 Market Entry Partner', '📋 Other',
        'Select timeline', '⚡ Urgent (< 2 weeks)', '📅 This Quarter', '📆 3–6 Months', '🔍 Just Exploring'),
      ('zh', 1,
        '发布需求', '告诉WeConnect网络您需要什么',
        '必填项标记为', 'PER GROUP将在1个工作日内回复',
        '基本信息', '需求详情', '商业参数', '联系方式',
        '主题', '需求类型', '需求描述', '目标',
        '目标地区', '预算', '时间',
        '姓名', '职位', '公司',
        '邮箱', '电话', '留言',
        '简要描述您的需求', '详细描述您的需求', '您希望达成什么目标?',
        '例如：新加坡、越南、欧盟', '例如：每月新币5千至1万5',
        '您的姓名', '职位', '公司名称',
        'your@email.com', '+65 xxxx xxxx', '简述需求',
        '提交需求', '提交中…',
        '已收到 — 我们会尽快与您联系。', 'PER GROUP将在1个工作日内回复您。',
        '必填', '邮箱格式错误', '请填写所有必填字段。',
        '🏢 办公室', '🔬 实验室', '🏭 厂房/工业用地', '💰 投资/融资', '🌏 市场进入合作', '📋 其他',
        '选择时间', '⚡ 紧急（2周内）', '📅 本季度', '📆 3-6个月', '🔍 初步了解')
    ON CONFLICT ("_locale", "_parent_id") DO NOTHING;

    INSERT INTO "cms"."contact_form_settings" ("id", "updated_at", "created_at")
      SELECT 1, now(), now()
      WHERE NOT EXISTS (SELECT 1 FROM "cms"."contact_form_settings" WHERE id = 1);
    INSERT INTO "cms"."contact_form_settings_locales" ("_locale", "_parent_id",
      "heading", "success_title", "success_message",
      "button_send_intro", "button_sending",
      "detail_label_size", "detail_label_zone", "detail_label_setup", "detail_label_lease", "detail_label_price")
    VALUES
      ('en', 1,
        'Connect with this partner', 'Introduction Sent!', 'WeConnect will facilitate the connection within 1–2 business days.',
        'Send Introduction', 'Sending…',
        'Size', 'Zone', 'Setup', 'Lease', 'Price'),
      ('zh', 1,
        '联系合作方', '介绍已发送！', 'WeConnect 将在1-2个工作日内协助对接。',
        '发送介绍', '发送中…',
        '面积', '区域', '设施', '租期', '价格')
    ON CONFLICT ("_locale", "_parent_id") DO NOTHING;

    -- ── 10. Pre-populate AboutBlock.milestones (4 items per existing block) ─
    INSERT INTO "cms"."pages_blocks_about_milestones" ("_order", "_parent_id", "id", "year")
    SELECT v._order, ab.id, gen_random_uuid()::text, v.year
    FROM "cms"."pages_blocks_about" ab
    CROSS JOIN (VALUES (1, '2009'), (2, '2015'), (3, '2019'), (4, '2024')) AS v(_order, year)
    WHERE NOT EXISTS (
      SELECT 1 FROM "cms"."pages_blocks_about_milestones" m WHERE m._parent_id = ab.id
    );

    INSERT INTO "cms"."pages_blocks_about_milestones_locales" ("_locale", "_parent_id", "title")
    SELECT 'en', m.id, CASE m.year
      WHEN '2009' THEN 'Founded in Singapore'
      WHEN '2015' THEN 'Expanded to 20+ countries'
      WHEN '2019' THEN 'E-Harbor ecosystem launched'
      WHEN '2024' THEN 'WeConnect AI platform'
    END
    FROM "cms"."pages_blocks_about_milestones" m
    WHERE NOT EXISTS (
      SELECT 1 FROM "cms"."pages_blocks_about_milestones_locales" ml
      WHERE ml._parent_id = m.id AND ml._locale = 'en'
    );

    INSERT INTO "cms"."pages_blocks_about_milestones_locales" ("_locale", "_parent_id", "title")
    SELECT 'zh', m.id, CASE m.year
      WHEN '2009' THEN '新加坡成立'
      WHEN '2015' THEN '拓展至20+国家'
      WHEN '2019' THEN 'E-Harbor 生态平台启动'
      WHEN '2024' THEN 'WeConnect 智能平台上线'
    END
    FROM "cms"."pages_blocks_about_milestones" m
    WHERE NOT EXISTS (
      SELECT 1 FROM "cms"."pages_blocks_about_milestones_locales" ml
      WHERE ml._parent_id = m.id AND ml._locale = 'zh'
    );

    -- ── 11. Pre-populate ClientsBlock.partnerTypes (4 items) ────────────────
    INSERT INTO "cms"."pages_blocks_clients_partner_types" ("_order", "_parent_id", "id", "icon")
    SELECT v._order, cb.id, gen_random_uuid()::text, v.icon::"cms"."enum_pages_blocks_clients_partner_types_icon"
    FROM "cms"."pages_blocks_clients" cb
    CROSS JOIN (VALUES
      (1, 'Globe'),
      (2, 'Building2'),
      (3, 'Handshake'),
      (4, 'Award')
    ) AS v(_order, icon)
    WHERE NOT EXISTS (
      SELECT 1 FROM "cms"."pages_blocks_clients_partner_types" p WHERE p._parent_id = cb.id
    );

    INSERT INTO "cms"."pages_blocks_clients_partner_types_locales" ("_locale", "_parent_id", "title", "examples")
    SELECT 'en', p.id,
      CASE p.icon::text
        WHEN 'Globe'     THEN 'Government & Trade Bodies'
        WHEN 'Building2' THEN 'Industry Associations'
        WHEN 'Handshake' THEN 'Professional Services'
        WHEN 'Award'     THEN 'Innovation Ecosystem'
      END,
      CASE p.icon::text
        WHEN 'Globe'     THEN 'Singapore EDB, Enterprise SG, CCPIT, regional chambers of commerce'
        WHEN 'Building2' THEN 'Manufacturing alliances, tech clusters, innovation parks across 53+ countries'
        WHEN 'Handshake' THEN 'Legal, accounting, IP, compliance, and ESG advisory firms — vetted and verified'
        WHEN 'Award'     THEN 'Universities, R&D labs, accelerators, venture funds, and technology transfer offices'
      END
    FROM "cms"."pages_blocks_clients_partner_types" p
    WHERE NOT EXISTS (
      SELECT 1 FROM "cms"."pages_blocks_clients_partner_types_locales" pl
      WHERE pl._parent_id = p.id AND pl._locale = 'en'
    );

    INSERT INTO "cms"."pages_blocks_clients_partner_types_locales" ("_locale", "_parent_id", "title", "examples")
    SELECT 'zh', p.id,
      CASE p.icon::text
        WHEN 'Globe'     THEN '政府与贸易机构'
        WHEN 'Building2' THEN '行业协会'
        WHEN 'Handshake' THEN '专业服务'
        WHEN 'Award'     THEN '创新生态'
      END,
      -- ZH examples are AI-suggested (originals were EN-only). Owner refines in 5b.4.
      CASE p.icon::text
        WHEN 'Globe'     THEN '新加坡经济发展局、新加坡企业发展局、中国国际贸易促进委员会及各地商会'
        WHEN 'Building2' THEN '53+国家的制造业联盟、科技产业集群与创新园区'
        WHEN 'Handshake' THEN '法律、会计、知识产权、合规与ESG咨询机构 — 经过认证'
        WHEN 'Award'     THEN '高校、研发实验室、孵化器、风险投资基金与技术转移办公室'
      END
    FROM "cms"."pages_blocks_clients_partner_types" p
    WHERE NOT EXISTS (
      SELECT 1 FROM "cms"."pages_blocks_clients_partner_types_locales" pl
      WHERE pl._parent_id = p.id AND pl._locale = 'zh'
    );

    -- ── 12. Pre-populate ClientsBlock.regions (6 items) ─────────────────────
    INSERT INTO "cms"."pages_blocks_clients_regions" ("_order", "_parent_id", "id", "count")
    SELECT v._order, cb.id, gen_random_uuid()::text, v.count
    FROM "cms"."pages_blocks_clients" cb
    CROSS JOIN (VALUES
      (1, '80+'),
      (2, '45+'),
      (3, '30+'),
      (4, '20+'),
      (5, '15+'),
      (6, '10+')
    ) AS v(_order, count)
    WHERE NOT EXISTS (
      SELECT 1 FROM "cms"."pages_blocks_clients_regions" r WHERE r._parent_id = cb.id
    );

    INSERT INTO "cms"."pages_blocks_clients_regions_locales" ("_locale", "_parent_id", "name")
    SELECT 'en', r.id, CASE r._order
      WHEN 1 THEN 'Southeast Asia'
      WHEN 2 THEN 'Europe'
      WHEN 3 THEN 'North America'
      WHEN 4 THEN 'Middle East'
      WHEN 5 THEN 'Africa'
      WHEN 6 THEN 'Oceania'
    END
    FROM "cms"."pages_blocks_clients_regions" r
    WHERE NOT EXISTS (
      SELECT 1 FROM "cms"."pages_blocks_clients_regions_locales" rl
      WHERE rl._parent_id = r.id AND rl._locale = 'en'
    );

    INSERT INTO "cms"."pages_blocks_clients_regions_locales" ("_locale", "_parent_id", "name")
    SELECT 'zh', r.id, CASE r._order
      WHEN 1 THEN '东南亚'
      WHEN 2 THEN '欧洲'
      WHEN 3 THEN '北美'
      WHEN 4 THEN '中东'
      WHEN 5 THEN '非洲'
      WHEN 6 THEN '大洋洲'
    END
    FROM "cms"."pages_blocks_clients_regions" r
    WHERE NOT EXISTS (
      SELECT 1 FROM "cms"."pages_blocks_clients_regions_locales" rl
      WHERE rl._parent_id = r.id AND rl._locale = 'zh'
    );

    -- ── 13. Pre-populate ClientsBlock parent locales (networkSubtitle, regionsHeading) ─
    INSERT INTO "cms"."pages_blocks_clients_locales" ("_locale", "_parent_id", "network_subtitle", "regions_heading")
    SELECT 'en', cb.id, 'A globally distributed partner network', 'Regional Presence'
    FROM "cms"."pages_blocks_clients" cb
    WHERE NOT EXISTS (
      SELECT 1 FROM "cms"."pages_blocks_clients_locales" cl
      WHERE cl._parent_id = cb.id AND cl._locale = 'en'
    );

    INSERT INTO "cms"."pages_blocks_clients_locales" ("_locale", "_parent_id", "network_subtitle", "regions_heading")
    SELECT 'zh', cb.id, '遍布全球的合作伙伴网络', '区域覆盖'
    FROM "cms"."pages_blocks_clients" cb
    WHERE NOT EXISTS (
      SELECT 1 FROM "cms"."pages_blocks_clients_locales" cl
      WHERE cl._parent_id = cb.id AND cl._locale = 'zh'
    );

    -- ── 14. Backfill new columns on existing locale tables ──────────────────
    -- HeroBlock.scrollHintLabel
    UPDATE "cms"."pages_blocks_hero_locales" SET "scroll_hint_label" = 'SCROLL'
      WHERE "_locale" = 'en' AND "scroll_hint_label" IS NULL;
    UPDATE "cms"."pages_blocks_hero_locales" SET "scroll_hint_label" = '向下滚动'
      WHERE "_locale" = 'zh' AND "scroll_hint_label" IS NULL;

    -- ServicesBlock.subtitle
    UPDATE "cms"."pages_blocks_services_locales" SET "subtitle" = 'End-to-end global services'
      WHERE "_locale" = 'en' AND "subtitle" IS NULL;
    UPDATE "cms"."pages_blocks_services_locales" SET "subtitle" = '全方位全球化服务'
      WHERE "_locale" = 'zh' AND "subtitle" IS NULL;
  `)
}

export async function down({ db, payload: _payload, req: _req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
    -- Reverse order: drop indexes/constraints implicitly via DROP TABLE CASCADE,
    -- then ALTER tables to remove added columns.
    DROP TABLE IF EXISTS "cms"."_pages_v_blocks_clients_locales" CASCADE;
    DROP TABLE IF EXISTS "cms"."_pages_v_blocks_clients_regions_locales" CASCADE;
    DROP TABLE IF EXISTS "cms"."_pages_v_blocks_clients_regions" CASCADE;
    DROP TABLE IF EXISTS "cms"."_pages_v_blocks_clients_partner_types_locales" CASCADE;
    DROP TABLE IF EXISTS "cms"."_pages_v_blocks_clients_partner_types" CASCADE;
    DROP TABLE IF EXISTS "cms"."_pages_v_blocks_about_milestones_locales" CASCADE;
    DROP TABLE IF EXISTS "cms"."_pages_v_blocks_about_milestones" CASCADE;

    DROP TABLE IF EXISTS "cms"."pages_blocks_clients_locales" CASCADE;
    DROP TABLE IF EXISTS "cms"."pages_blocks_clients_regions_locales" CASCADE;
    DROP TABLE IF EXISTS "cms"."pages_blocks_clients_regions" CASCADE;
    DROP TABLE IF EXISTS "cms"."pages_blocks_clients_partner_types_locales" CASCADE;
    DROP TABLE IF EXISTS "cms"."pages_blocks_clients_partner_types" CASCADE;
    DROP TABLE IF EXISTS "cms"."pages_blocks_about_milestones_locales" CASCADE;
    DROP TABLE IF EXISTS "cms"."pages_blocks_about_milestones" CASCADE;

    DROP TABLE IF EXISTS "cms"."contact_form_settings_locales" CASCADE;
    DROP TABLE IF EXISTS "cms"."contact_form_settings" CASCADE;
    DROP TABLE IF EXISTS "cms"."requirement_form_settings_locales" CASCADE;
    DROP TABLE IF EXISTS "cms"."requirement_form_settings" CASCADE;
    DROP TABLE IF EXISTS "cms"."weconnect_settings_locales" CASCADE;
    DROP TABLE IF EXISTS "cms"."weconnect_settings" CASCADE;
    DROP TABLE IF EXISTS "cms"."footer_settings_locales" CASCADE;
    DROP TABLE IF EXISTS "cms"."footer_settings" CASCADE;
    DROP TABLE IF EXISTS "cms"."nav_settings_locales" CASCADE;
    DROP TABLE IF EXISTS "cms"."nav_settings" CASCADE;

    ALTER TABLE "cms"."pages_blocks_hero_locales" DROP COLUMN IF EXISTS "scroll_hint_label";
    ALTER TABLE "cms"."_pages_v_blocks_hero_locales" DROP COLUMN IF EXISTS "scroll_hint_label";
    ALTER TABLE "cms"."pages_blocks_services_locales" DROP COLUMN IF EXISTS "subtitle";
    ALTER TABLE "cms"."_pages_v_blocks_services_locales" DROP COLUMN IF EXISTS "subtitle";

    DROP TYPE IF EXISTS "cms"."enum__pages_v_blocks_clients_partner_types_icon";
    DROP TYPE IF EXISTS "cms"."enum_pages_blocks_clients_partner_types_icon";
  `)
}
