/**
 * Payload CMS admin panel.
 * Handled entirely by @payloadcms/next — do not add custom code here.
 *
 * Access: /admin
 * SECURITY: Disallowed in robots.txt. Login requires Payload Users collection credentials.
 *
 * Next.js 15: params and searchParams are Promises and must be forwarded explicitly.
 * importMap is auto-generated by withPayload / `npm run generate:importmap`.
 */
import { RootPage, generatePageMetadata } from '@payloadcms/next/views'
import configPromise from '@payload-config'
import { importMap } from '../importMap.js'

type Args = {
  params: Promise<{ segments: string[] }>
  searchParams: Promise<{ [key: string]: string | string[] }>
}

export const generateMetadata = ({ params, searchParams }: Args) =>
  generatePageMetadata({ config: configPromise, params, searchParams })

export default function Page({ params, searchParams }: Args) {
  return (
    <RootPage
      config={configPromise}
      params={params}
      searchParams={searchParams}
      importMap={importMap}
    />
  )
}
